services:
  - type: web
    name: agriguard-backend
    env: python
    rootDir: backend
    buildCommand: ./build.sh
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.10.12
